apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP
  #type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      #nodePort: 32002
